services:
  airflow-init:
    build: .
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=PAqBeGJLJTYFzVkOGHWIYXdLO7XdXz5yTdxAGJe9ezM=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./utils:/opt/airflow/scripts/utils
      - ./data:/opt/airflow/scripts/data
      - ./model_bank:/opt/airflow/scripts/model_bank
      - ./data_pipeline:/opt/airflow/scripts/data_pipeline
      - ./ml_pipeline:/opt/airflow/scripts/ml_pipeline
    entrypoint: >
      /bin/bash -c "airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true"

  airflow-webserver:
    build: .
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=PAqBeGJLJTYFzVkOGHWIYXdLO7XdXz5yTdxAGJe9ezM=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./utils:/opt/airflow/scripts/utils
      - ./data:/opt/airflow/scripts/data
      - ./model_bank:/opt/airflow/scripts/model_bank
      - ./data_pipeline:/opt/airflow/scripts/data_pipeline
      - ./ml_pipeline:/opt/airflow/scripts/ml_pipeline
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    build: .
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=PAqBeGJLJTYFzVkOGHWIYXdLO7XdXz5yTdxAGJe9ezM=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./utils:/opt/airflow/scripts/utils
      - ./data:/opt/airflow/scripts/data
      - ./model_bank:/opt/airflow/scripts/model_bank
      - ./data_pipeline:/opt/airflow/scripts/data_pipeline
      - ./ml_pipeline:/opt/airflow/scripts/ml_pipeline
    command: scheduler

volumes:
  airflow_data: